### ISSUE TITLE
报登录页不存在

### ISSUE THREAD

**Issue by 4723725** [jitamin/jitamin#311]
- Jitamin Version: 0.5.0
- PHP Version: 7.2.12
- Database Driver & Version: mysql 8.3

### Description:
输入系统地址后回车，报找不到登录页。错误如下。是否是哪里配置错误，还是代码故障？

Not Found The requested URL /login was not found on this server.

### Steps To Reproduce:

**Comment by liuguodong1019** [comment]
兄弟  你解决了吗   我也遇到了同样的问题

**Comment by perlinlee** [comment]
同样问题 ，报/login 报找不到 ， php7.1.29 ，有解决的吗？

**Comment by 4723725** [comment]
没有找到。可能和部署相关。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: perlinlee <notifications@github.com>
发送时间: 2019年5月28日 14:46
收件人: jitamin/jitamin <jitamin@noreply.github.com>
抄送: 4723725 <4723725@qq.com>, Author <author@noreply.github.com>
主题: 回复：[jitamin/jitamin] 报登录页不存在 (#311)

**Comment by perlinlee** [comment]
部署 composer 都成功了

**Comment by perlinlee** [comment]
> 没有找到。可能和部署相关。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: perlinlee <notifications@github.com> 发送时间: 2019年5月28日 14:46 收件人: jitamin/jitamin <jitamin@noreply.github.com> 抄送: 4723725 <4723725@qq.com>, Author <author@noreply.github.com> 主题: 回复：[jitamin/jitamin] 报登录页不存在 (#311)

兄弟你解决了吗？是php版本问题吗？

**Comment by liuguodong1019** [comment]
没解决呢  应该不是版本问题，我本地版本和服务器版本是一样的，本地是没问题的




------------------ 原始邮件 ------------------
发件人: "perlinlee"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 下午2:50
收件人: "jitamin/jitamin"<jitamin@noreply.github.com>; 
抄送: "刘国栋   简历"<331787444@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jitamin/jitamin] 报登录页不存在 (#311)



 
没有找到。可能和部署相关。 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: perlinlee notifications@github.com 发送时间: 2019年5月28日 14:46 收件人: jitamin/jitamin jitamin@noreply.github.com 抄送: 4723725 4723725@qq.com, Author author@noreply.github.com 主题: 回复：[jitamin/jitamin] 报登录页不存在 (#311)
  
兄弟你解决了吗？是php版本问题吗？

**Comment by 4723725** [comment]
经过尝试，主版本是不行的。0.5；0.49版本在服务器都可以的。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: liuguodong1019 <notifications@github.com>
发送时间: 2019年5月28日 14:51
收件人: jitamin/jitamin <jitamin@noreply.github.com>
抄送: 4723725 <4723725@qq.com>, Author <author@noreply.github.com>
主题: 回复：[jitamin/jitamin] 报登录页不存在 (#311)



没解决呢  应该不是版本问题，我本地版本和服务器版本是一样的，本地是没问题的 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "perlinlee"<notifications@github.com>;  
 发送时间: 2019年5月28日(星期二) 下午2:50 
 收件人: "jitamin/jitamin"<jitamin@noreply.github.com>;  
 抄送: "刘国栋   简历"<331787444@qq.com>; "Comment"<comment@noreply.github.com>;  
 主题: Re: [jitamin/jitamin] 报登录页不存在 (#311) 
 
 
 
   
 没有找到。可能和部署相关。 发自我的iPhone 
  … 
  ------------------ 原始邮件 ------------------ 发件人: perlinlee notifications@github.com 发送时间: 2019年5月28日 14:46 收件人: jitamin/jitamin jitamin@noreply.github.com 抄送: 4723725 4723725@qq.com, Author author@noreply.github.com 主题: 回复：[jitamin/jitamin] 报登录页不存在 (#311) 
    
 兄弟你解决了吗？是php版本问题吗？

**Comment by perlinlee** [comment]
我试试0.49 ， 一会再反馈一下。

**Comment by liuguodong1019** [comment]
好的




------------------ 原始邮件 ------------------
发件人: "perlinlee"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 下午2:54
收件人: "jitamin/jitamin"<jitamin@noreply.github.com>; 
抄送: "刘国栋   简历"<331787444@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jitamin/jitamin] 报登录页不存在 (#311)




我试试0.49 ， 一会再反馈一下。

**Comment by perlinlee** [comment]
0.49 报一样的错误！

**Comment by liuguodong1019** [comment]
哎      是不是框架的路由写的有问题




------------------ 原始邮件 ------------------
发件人: "perlinlee"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 下午4:01
收件人: "jitamin/jitamin"<jitamin@noreply.github.com>; 
抄送: "刘国栋   简历"<331787444@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jitamin/jitamin] 报登录页不存在 (#311)




0.49 报一样的错误！

**Comment by perlinlee** [comment]
0.48 同样方法安装成功，但终于页面报出了一个错误，看来像是 picodb安装问题
Class 'PicoDb\\UrlParser' not found in /opt/apache/htdocs/jita4/bootstrap/autoload.php:14\nStack trace:\n#0 /opt/apache/htdocs/jita4/public/index.php(13): require()\n#1 {main}\n  thrown in /opt/apache/htdocs/jita4/bootstrap/autoload.php on line 14

**Comment by liuguodong1019** [comment]
加油  真相越来越近了




------------------ 原始邮件 ------------------
发件人: "perlinlee"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 下午4:22
收件人: "jitamin/jitamin"<jitamin@noreply.github.com>; 
抄送: "刘国栋   简历"<331787444@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jitamin/jitamin] 报登录页不存在 (#311)




0.48 同样方法安装成功，但终于页面报出了一个错误，看来像是 picodb安装问题
 Class 'PicoDb\UrlParser' not found in /opt/apache/htdocs/jita4/bootstrap/autoload.php:14\nStack trace:\n#0 /opt/apache/htdocs/jita4/public/index.php(13): require()\n#1 {main}\n  thrown in /opt/apache/htdocs/jita4/bootstrap/autoload.php on line 14

**Comment by perlinlee** [comment]
试了3个版本，安装过程中的错误全部解决，但仍然没有成功，猜想作者的源代码有些问题，不知道有些人为什么能运行成功。也许是环境问题，但感觉不太可能，作者去哪了啊？

**Comment by liuguodong1019** [comment]
实在不行你试试  用kanboard  ，看看怎么样，jitamin就是基于它开发的




------------------ 原始邮件 ------------------
发件人: "perlinlee"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 下午4:26
收件人: "jitamin/jitamin"<jitamin@noreply.github.com>; 
抄送: "刘国栋   简历"<331787444@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jitamin/jitamin] 报登录页不存在 (#311)




试了3个版本，安装过程中的错误全部解决，但仍然没有成功，猜想作者的源代码有些问题，不知道有些人为什么能运行成功。也许是环境问题，但感觉不太可能，作者去哪了啊？

**Comment by perlinlee** [comment]
谢谢，kanboard 有实际工时填写吗？

> 实在不行你试试 用kanboard ，看看怎么样，jitamin就是基于它开发的
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "perlinlee"<notifications@github.com>; 发送时间: 2019年5月28日(星期二) 下午4:26 收件人: "jitamin/jitamin"<jitamin@noreply.github.com>; 抄送: "刘国栋 简历"<331787444@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [jitamin/jitamin] 报登录页不存在 (#311) 试了3个版本，安装过程中的错误全部解决，但仍然没有成功，猜想作者的源代码有些问题，不知道有些人为什么能运行成功。也许是环境问题，但感觉不太可能，作者去哪了啊？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by liuguodong1019** [comment]
好像是有的




------------------ 原始邮件 ------------------
发件人: "perlinlee"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 下午4:40
收件人: "jitamin/jitamin"<jitamin@noreply.github.com>; 
抄送: "刘国栋   简历"<331787444@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jitamin/jitamin] 报登录页不存在 (#311)




谢谢，kanboard 有实际工时填写吗？
  
实在不行你试试 用kanboard ，看看怎么样，jitamin就是基于它开发的
 …
 ------------------ 原始邮件 ------------------ 发件人: "perlinlee"notifications@github.com; 发送时间: 2019年5月28日(星期二) 下午4:26 收件人: "jitamin/jitamin"jitamin@noreply.github.com; 抄送: "刘国栋 简历"331787444@qq.com; "Comment"comment@noreply.github.com; 主题: Re: [jitamin/jitamin] 报登录页不存在 (#311) 试了3个版本，安装过程中的错误全部解决，但仍然没有成功，猜想作者的源代码有些问题，不知道有些人为什么能运行成功。也许是环境问题，但感觉不太可能，作者去哪了啊？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by 4723725** [comment]
有，但是在实际使用中，很容易忘记填写。关注的是任务的进展。除非要下管理要求。而且实际工时填写也不是很准确。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: perlinlee <notifications@github.com>
发送时间: 2019年5月28日 16:40
收件人: jitamin/jitamin <jitamin@noreply.github.com>
抄送: 4723725 <4723725@qq.com>, Author <author@noreply.github.com>
主题: 回复：[jitamin/jitamin] 报登录页不存在 (#311)




谢谢，kanboard 有实际工时填写吗？
  
实在不行你试试 用kanboard ，看看怎么样，jitamin就是基于它开发的
 …
 ------------------ 原始邮件 ------------------ 发件人: "perlinlee"notifications@github.com; 发送时间: 2019年5月28日(星期二) 下午4:26 收件人: "jitamin/jitamin"jitamin@noreply.github.com; 抄送: "刘国栋 简历"331787444@qq.com; "Comment"comment@noreply.github.com; 主题: Re: [jitamin/jitamin] 报登录页不存在 (#311) 试了3个版本，安装过程中的错误全部解决，但仍然没有成功，猜想作者的源代码有些问题，不知道有些人为什么能运行成功。也许是环境问题，但感觉不太可能，作者去哪了啊？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by perlinlee** [comment]
好的，谢谢两位！我试装一下 kanborard!

**Comment by veavolup** [comment]
我试了，可以这样解决：
方法1：打开apache的rewrite功能
方法2：修改config/config.php，'enable_url_rewrite' => false

**Comment by hintzczl** [comment]
我也报找不到,后来用phpstudy弄了个集成系统,就解决了

**Comment by wangxi83** [comment]
假开源

**Comment by ForeverParker** [comment]
Please check the hidden file .htaccess in the public folder.
The load module defined maybe diffent from your Apache conf files. E.g <IfModule rewrite_module.c> should write as <IfModule rewrite_module>

**Comment by RoyeeW** [comment]
> 我试了，可以这样解决：
> 方法1：打开apache的rewrite功能
> 方法2：修改config/config.php，'enable_url_rewrite' => false

方法2解决。 用phpstudy pro 部署
