### ISSUE TITLE
是不是不能装了 一直报错

### ISSUE THREAD

**Issue by gitcomy** [jitamin/jitamin#335]
`Deprecation Notice: Class JsonRPC\Response\ResponseParser located in ./vendor/jitamin/json-rpc/src/Response/ResponseParser.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`

**Comment by gitcomy** [comment]
类似这样的一堆

**Comment by linjiadashu** [comment]
我装好了。

**Comment by yagao0o** [comment]
装composer的时候不要用2.0+的版本，用1+的版本，我用1.10.17安装成功了

**Comment by cbxbw** [comment]
> 装composer的时候不要用2.0+的版本，用1+的版本，我用1.10.17安装成功了

Fatal error: Uncaught exception 'LogicException' with message 'Database driver not supported' in /www/wwwroot/kanban.cc_6901/app/Providers/DatabaseServiceProvider.php:62 Stack trace: #0 /www/wwwroot/kanban.cc_6901/app/Providers/DatabaseServiceProvider.php(33): Jitamin\Providers\DatabaseServiceProvider->getInstance() #1 /www/wwwroot/kanban.cc_6901/vendor/pimple/pimple/src/Pimple/Container.php(274): Jitamin\Providers\DatabaseServiceProvider->register(Object(Pimple\Container)) #2 /www/wwwroot/kanban.cc_6901/bootstrap/app.php(17): Pimple\Container->register(Object(Jitamin\Providers\DatabaseServiceProvider)) #3 /www/wwwroot/kanban.cc_6901/public/index.php(16): require_once('/www/wwwroot/ka...') #4 {main} thrown in /www/wwwroot/kanban.cc_6901/app/Providers/DatabaseServiceProvider.php on line 62    
还是报错啊， composer 1.10.17  + php 5.6

**Comment by cbxbw** [comment]
> 装composer的时候不要用2.0+的版本，用1+的版本，我用1.10.17安装成功了

windows 环境没问题，linux 环境就报错
